name: React App CI/CD with Docker

on:
  push:
    branches:
      - master # Replace with your branch name if different

jobs:
  build-and-deploy:
    runs-on: self-hosted # Use your self-hosted GitHub Runner
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Matches the version in your Dockerfile

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t esbe1546/react-app:latest .
          docker push esbe1546/react-app:latest

      - name: Deploy Docker Container
        run: |
          docker pull esbe1546/react-app:latest
          docker stop react-app || true
          docker rm react-app || true
          docker run -d --name react-app -p 3000:3000 esbe1546/react-app:latest
